--Q1. What is the total revenue generated by male vs. female customers?

SELECT SUM(purchase_amount),gender
FROM `data-analytics5054.analytics.customer`
GROUP BY gender

-- From the data, it is observed that males have generated almost twice the revenue compared to females.